# Generated by Django 5.2.17 on 2026-09-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamingAccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('game', models.CharField(choices=[('dota2', 'Dota 2')], max_length=50)),
                ('provider', models.CharField(choices=[('stratz', 'STRATZ')], max_length=50)),
                ('external_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gaming_accounts',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'game'), name='unique_user_game')],
            },
        ),
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_match_id', models.BigIntegerField()),
                ('hero_id', models.IntegerField(blank=True, null=True)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('is_victory', models.BooleanField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('game_mode', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gaming_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='persistence.gamingaccountmodel')),
            ],
            options={
                'db_table': 'matches',
                'constraints': [models.UniqueConstraint(fields=('gaming_account', 'external_match_id'), name='unique_account_match')],
            },
        ),
    ]
